### ISSUE TITLE
Replace UselessFodder video ?

### ISSUE THREAD

**Issue by ImplicitDeny** [ofpisnotdead-com/awesome-reforger#4]
UselessFodder just published a new, more efficient video on how to create custom coop missions for Reforger : https://www.youtube.com/watch?v=WNL_oFhlmLU

Maybe we should replace the old, 2h20mn recorded stream where he wander around the editor having no idea what to do ? It is currently referenced in the document under "Mission making", third entry.

I'm opening this issue because I didn't have time to watch the entire new video yet. If not already replaced, I might pull-request this evening, once I finished watching the video.

Greetings !

**Comment by simi** [comment]
I'll check on the video, we can add this entry for now and make it on the top of the list and remove the old entry later.

**Comment by simi** [comment]
Btw. if you're interesting in keeping this list updated I can give you access. I do plan big update (mostly based on GitHub search for `Reforger` term) this week. But there is a lot of interesting stuff on Discord and Twitter happening as well and I'm afraid I'm not able to cover everything.

**Comment by ImplicitDeny** [comment]
I would be glad to help !

However I think we should have a moment to think about what to do with this repo : with the official doc coming along and the community wiki growing, there is a risk of duplicated information. What kind of documentation this repo should retain ? Should it be a sort of "entry point of all modding matters" ? Or more like a "How to do this or that" ?

**Comment by simi** [comment]
Official docs are not opened to everyone to contribute (you need to get account somehow manually approved to get access to Wiki) and also not every content is welcomed in there. That's the reason for this list.
